/**
 * Maps team names to ISO 3166-1 alpha-2 country codes (lowercase).
 * Used to load circular flags from hatscripts.github.io/circle-flags.
 *
 * Special codes supported by circle-flags:
 *   gb-eng  England
 *   gb-sct  Scotland
 *   gb-wls  Wales
 *   gb-nir  Northern Ireland
 *   xk      Kosovo
 */
export const COUNTRY_CODES = {
  // ── CONCACAF ───────────────────────────────────────────
  USA:                        'us',
  'United States':            'us',
  Mexico:                     'mx',
  Canada:                     'ca',
  'Costa Rica':               'cr',
  Panama:                     'pa',
  Jamaica:                    'jm',
  Honduras:                   'hn',
  'El Salvador':              'sv',
  Guatemala:                  'gt',
  'Trinidad and Tobago':      'tt',
  Cuba:                       'cu',
  Haiti:                      'ht',
  Belize:                     'bz',
  Bermuda:                    'bm',
  Guyana:                     'gy',
  'Antigua and Barbuda':      'ag',
  Barbados:                   'bb',
  Grenada:                    'gd',
  'Saint Kitts and Nevis':    'kn',
  'Saint Lucia':              'lc',
  'Saint Vincent':            'vc',
  'Dominican Republic':       'do',

  // ── CONMEBOL ───────────────────────────────────────────
  Argentina:   'ar',
  Brazil:      'br',
  Uruguay:     'uy',
  Colombia:    'co',
  Venezuela:   've',
  Chile:       'cl',
  Ecuador:     'ec',
  Bolivia:     'bo',
  Paraguay:    'py',
  Peru:        'pe',

  // ── UEFA ───────────────────────────────────────────────
  Germany:                    'de',
  France:                     'fr',
  Spain:                      'es',
  England:                    'gb-eng',
  Portugal:                   'pt',
  Netherlands:                'nl',
  Italy:                      'it',
  Belgium:                    'be',
  Croatia:                    'hr',
  Serbia:                     'rs',
  Switzerland:                'ch',
  Poland:                     'pl',
  Denmark:                    'dk',
  Austria:                    'at',
  Ukraine:                    'ua',
  Hungary:                    'hu',
  Norway:                     'no',
  Scotland:                   'gb-sct',
  Turkey:                     'tr',
  Romania:                    'ro',
  Slovakia:                   'sk',
  Albania:                    'al',
  Georgia:                    'ge',
  'Czech Republic':           'cz',
  Czechia:                    'cz',
  Wales:                      'gb-wls',
  Slovenia:                   'si',
  Sweden:                     'se',
  Greece:                     'gr',
  Finland:                    'fi',
  Iceland:                    'is',
  Ireland:                    'ie',
  'Northern Ireland':         'gb-nir',
  'Bosnia and Herzegovina':   'ba',
  Montenegro:                 'me',
  'North Macedonia':          'mk',
  Kosovo:                     'xk',
  Luxembourg:                 'lu',
  Armenia:                    'am',
  Azerbaijan:                 'az',
  Kazakhstan:                 'kz',
  Belarus:                    'by',
  Bulgaria:                   'bg',
  Latvia:                     'lv',
  Lithuania:                  'lt',
  Estonia:                    'ee',
  Malta:                      'mt',
  Cyprus:                     'cy',
  'Faroe Islands':            'fo',
  Gibraltar:                  'gi',
  Andorra:                    'ad',
  Moldova:                    'md',
  'San Marino':               'sm',
  Russia:                     'ru',
  Israel:                     'il',

  // ── CAF (Africa) ───────────────────────────────────────
  Morocco:                    'ma',
  Senegal:                    'sn',
  Egypt:                      'eg',
  Nigeria:                    'ng',
  Cameroon:                   'cm',
  'Ivory Coast':              'ci',
  "Côte d'Ivoire":            'ci',
  Ghana:                      'gh',
  'South Africa':             'za',
  Algeria:                    'dz',
  Tunisia:                    'tn',
  Mali:                       'ml',
  'Burkina Faso':             'bf',
  Guinea:                     'gn',
  'DR Congo':                 'cd',
  Congo:                      'cg',
  Tanzania:                   'tz',
  Uganda:                     'ug',
  Kenya:                      'ke',
  Zimbabwe:                   'zw',
  Zambia:                     'zm',
  Ethiopia:                   'et',
  Mozambique:                 'mz',
  Sudan:                      'sd',
  Benin:                      'bj',
  Angola:                     'ao',
  Gabon:                      'ga',
  'Equatorial Guinea':        'gq',
  'Cape Verde':               'cv',
  Comoros:                    'km',
  Libya:                      'ly',
  Gambia:                     'gm',
  Mauritania:                 'mr',
  Namibia:                    'na',
  Rwanda:                     'rw',
  Togo:                       'tg',
  Liberia:                    'lr',
  'Sierra Leone':             'sl',
  Niger:                      'ne',
  Chad:                       'td',
  Malawi:                     'mw',
  Madagascar:                 'mg',
  Botswana:                   'bw',
  Eswatini:                   'sz',
  Lesotho:                    'ls',
  Djibouti:                   'dj',
  Eritrea:                    'er',
  Somalia:                    'so',

  // ── AFC (Asia) ──────────────────────────────────────────
  Japan:                      'jp',
  'South Korea':              'kr',
  'Korea Republic':           'kr',
  'Saudi Arabia':             'sa',
  Iran:                       'ir',
  Australia:                  'au',
  Qatar:                      'qa',
  UAE:                        'ae',
  'United Arab Emirates':     'ae',
  Bahrain:                    'bh',
  Iraq:                       'iq',
  Jordan:                     'jo',
  Kuwait:                     'kw',
  Oman:                       'om',
  China:                      'cn',
  'China PR':                 'cn',
  India:                      'in',
  Thailand:                   'th',
  Vietnam:                    'vn',
  Indonesia:                  'id',
  Philippines:                'ph',
  Malaysia:                   'my',
  Singapore:                  'sg',
  Myanmar:                    'mm',
  Uzbekistan:                 'uz',
  Kyrgyzstan:                 'kg',
  Tajikistan:                 'tj',
  Afghanistan:                'af',
  Palestine:                  'ps',
  Lebanon:                    'lb',
  Syria:                      'sy',
  Yemen:                      'ye',
  Nepal:                      'np',
  'Sri Lanka':                'lk',
  Pakistan:                   'pk',
  Bangladesh:                 'bd',
  Mongolia:                   'mn',
  'North Korea':              'kp',
  'Hong Kong':                'hk',
  Maldives:                   'mv',
  'Chinese Taipei':           'tw',
  Macau:                      'mo',

  // ── OFC (Oceania) ───────────────────────────────────────
  'New Zealand':              'nz',
  Fiji:                       'fj',
  'Papua New Guinea':         'pg',
  'Solomon Islands':          'sb',
  Tahiti:                     'pf',
  Vanuatu:                    'vu',
  'New Caledonia':            'nc',
  Samoa:                      'ws',
  'American Samoa':           'as',
  Tonga:                      'to',
  'Cook Islands':             'ck',
};

export function getCountryCode(teamName) {
  return COUNTRY_CODES[teamName] ?? null;
}
